# Dependencies
markdown:         redcarpet
highligher:       rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ben Lindsey
tagline:          Make it work. Make it right. Make it fast. Make it small.
url:              http://www.benlindsey.com
paginate:         5 
baseurl:          /
author:
  name:           Ben Lindsey
  url:            https://github.com/blindsey

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/blindsey/blindsey.github.io

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
